"use client";

import React, { useState, useRef, useEffect } from "react";
import { Send, ArrowUp, Sparkles } from "lucide-react";

export default function ChatInput({ onSendMessage, isLoading }) {
  const [inputValue, setInputValue] = useState("");
  const textareaRef = useRef(null);

  // Auto-resize textarea logic
  useEffect(() => {
    const textarea = textareaRef.current;
    if (!textarea) return;

    // Reset height to calculate scrollHeight
    textarea.style.height = "auto";
    // Set to scrollHeight, clamped between min and max heights
    textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
  }, [inputValue]);

  const handleSubmit = (e) => {
    e?.preventDefault();
    if (!inputValue.trim() || isLoading) return;

    onSendMessage(inputValue.trim());
    setInputValue("");
    
    // Reset textarea height
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="w-full border-t border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 px-4 py-4 md:px-8 select-none transition-colors duration-200">
      <form onSubmit={handleSubmit} className="max-w-3xl mx-auto relative flex items-center">
        {/* Glow focus ring wrapper */}
        <div className="w-full relative flex items-center bg-slate-100 dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 focus-within:border-indigo-500/50 focus-within:ring-2 focus-within:ring-indigo-600/10 rounded-2xl transition-all duration-200 shadow-sm">
          
          {/* AI Helper Visual Indicator */}
          <div className="pl-3.5 text-slate-400 dark:text-zinc-500 hidden sm:block">
            <Sparkles className="w-4 h-4 text-indigo-500/70 dark:text-indigo-400/60" />
          </div>

          <textarea
            ref={textareaRef}
            rows={1}
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={isLoading ? "Bot is researching query..." : "Ask about salaries, average wages, market trends..."}
            disabled={isLoading}
            className="flex-1 w-full bg-transparent outline-none border-none py-3 px-3.5 text-sm text-slate-900 dark:text-zinc-100 placeholder-slate-400 dark:placeholder-zinc-500 max-h-[200px] overflow-y-auto resize-none disabled:cursor-not-allowed leading-relaxed"
          />

          {/* Submit Trigger Button */}
          <div className="pr-2 py-2 flex items-center">
            <button
              type="submit"
              disabled={!inputValue.trim() || isLoading}
              className={`p-2.5 rounded-xl flex items-center justify-center transition-all cursor-pointer ${
                inputValue.trim() && !isLoading
                  ? "bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-600/20 hover:scale-[1.05]"
                  : "bg-slate-200 dark:bg-zinc-800 text-slate-400 dark:text-zinc-600 cursor-not-allowed"
              }`}
              title="Submit message"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>
        </div>
      </form>
      <div className="max-w-3xl mx-auto mt-2 text-[10px] text-center text-slate-400 dark:text-zinc-600 font-medium">
        Insights are generated by analyzing database chunk citations retrieved using FAISS vector matches.
      </div>
    </div>
  );
}
